INSERT INTO avaliacao_questao (questaotipo_id, aplicacao_id, questao_descricao) VALUES
# EIXO 1 
('multiplaEscolha','autoAvaliacao','Acesso/Atendimento da Coordenação do Curso'),
('multiplaEscolha','autoAvaliacao','Biblioteca'),
('multiplaEscolha','autoAvaliacao','Condições físicas dos sanitários'),
('multiplaEscolha','autoAvaliacao','Espaço de convivência/lanchonete'),
('multiplaEscolha','autoAvaliacao','Qualidade (conforto, iluminação e limpeza) das salas de aula'),
('multiplaEscolha','autoAvaliacao','Qualidade de atendimento da secretaria'),
('multiplaEscolha','autoAvaliacao','Qualidade dos serviços de reprografia (xerox)'),
('multiplaEscolha','autoAvaliacao','Qualidade dos serviços financeiros'),
('multiplaEscolha','autoAvaliacao','Recursos computacionais (laboratório/equipamentos)'),
('multiplaEscolha','autoAvaliacao','Serviços de segurança'),
('multiplaEscolha','autoAvaliacao','Sistema acadêmico e site institucional'),
('multiplaEscolha','autoAvaliacao','Qualidade do ensino ofertado'),
('multiplaEscolha','autoAvaliacao','Trabalhos de campo/palestras ofertadas pela Instituição'),
# EIXO 2
('multiplaEscolha','autoAvaliacao','Considerando a equidade de oportunidades, a formação cidadã, o comprometimento ético da comunidade acadêmico-administrativa e os princípios de justiça social, a implementação da responsabilidade social nas ações da FABRAS é:'),
('multiplaEscolha','autoAvaliacao','O atendimento da FABRAS à missão da FABRAS, expressa como exercer uma ação integrada das suas atividades educacionais visando a geração, a sistematização e disseminação do conhecimento, para a formação de empreendedores capazes de promover a transformação e o desenvolvimento social, econômico e cultural da comunidade em que está inserida, está:'),
('multiplaEscolha','autoAvaliacao','Considerando a frequência, quantidade e qualidade das atividades e as oportunidades de participação, o desenvolvimento de atividades artísticas e culturais na FABRAS é:'),
('multiplaEscolha','autoAvaliacao','Considerando o respeito à natureza e a busca pelo equilíbrio ambiental nas práticas permanentes no cotidiano da vida acadêmica, o desenvolvimento sustentável é um tema tratado de forma:'),
('multiplaEscolha','autoAvaliacao','Considerando quantidade, qualidade e frequência, as ações extracurriculares relacionadas à educação na formação do profissional como um todo na unidade são:'),
('multiplaEscolha','autoAvaliacao','Considerando as práticas institucionais e políticas relacionadas, a inclusão de pessoas com deficiência e transtorno de neurodesenvolvimento na FABRAS é:'),
('multiplaEscolha','autoAvaliacao','Os programas, projetos, cursos e eventos implantados na FABRAS apoiam o desenvolvimento econômico local e regional de forma:'),
# EIXO 3
('multiplaEscolha','autoAvaliacao','Planejamento das atividades pelo professor'),
('multiplaEscolha','autoAvaliacao','Articulação das disciplinas com as demais do curso'),
('multiplaEscolha','autoAvaliacao','Seguiu o plano de ensino apresentado de forma efetiva e coerente?'),
('multiplaEscolha','autoAvaliacao','Facilidade em se comunicar com os estudantes?'),
('multiplaEscolha','autoAvaliacao','Incentivo aos debates dos conteúdos abordados?'),
('multiplaEscolha','autoAvaliacao','Pontualidade no início e término das aulas'),
('multiplaEscolha','autoAvaliacao','Utilizou recursos de forma coerente e eficiente'),
('multiplaEscolha','autoAvaliacao','Esclarecimentos de dúvidas'),
('multiplaEscolha','autoAvaliacao','Estimulo ao aprofundamento dos temas propostos'),
('multiplaEscolha','autoAvaliacao','Consonância dos conteúdos da disciplina e as avaliações da aprendizagem '),
('multiplaEscolha','autoAvaliacao','Considerando o estímulo institucional, o apoio da FABRAS a adoção de práticas inovadoras no ensino é:'),
('multiplaEscolha','autoAvaliacao','Considerando o estímulo institucional, o apoio da FABRAS a adoção de práticas inovadoras na pesquisa é:'),
('multiplaEscolha','autoAvaliacao','Considerando que o objetivo maior de todas as atividades de ensino é a aprendizagem, o compromisso dos professores na FABRAS é:'),
('multiplaEscolha','autoAvaliacao','Com o intuito de assegurar a permanência e o sucesso dos estudantes nos cursos, os processos de ensino na FABRAS são:'),
# EIXO 4
('multiplaEscolha','autoAvaliacao','Considerando horários de funcionamento e resolutividade de problemas encaminhados ao setor, os serviços prestados pelo registro acadêmico (Secretaria) são:'),
('multiplaEscolha','autoAvaliacao','Considerando a orientação pedagógica e o apoio a pais e alunos, os serviços prestados pelo setor pedagógico são:'),
('multiplaEscolha','autoAvaliacao','Considerando os temas relacionados aos auxílios financeiros, os serviços prestados pelo setor de assistência estudantil (Financeiro/Direção) são:'),
('multiplaEscolha','autoAvaliacao','Considerando a disponibilidade de tempo, a infraestrutura disponível e a atenção dispensada, o atendimento do professor às dúvidas dos alunos, fora dos horários de aulas, é:'),
('multiplaEscolha','autoAvaliacao','A incorporação de valores ético-políticos e conteúdos histórico-científicos na formação profissional, em oposição a simples formação para o mercado de trabalho na FABRAS é:'),
('multiplaEscolha','autoAvaliacao','A integração de conhecimentos gerais e específicos, básicos e profissionais e teóricos e práticos nos currículos e práticas pedagógicas dos cursos da FABRAS é:'),
('multiplaEscolha','autoAvaliacao','Considerando a quantidade de visitas, qualidade dos locais e a contribuição que essas visitas levam a formação profissional, as visitas técnicas organizadas pela FABRAS são:'),
('multiplaEscolha','autoAvaliacao','O acompanhamento dos estágios supervisionados, por meio de professores orientadores é:'),
('multiplaEscolha','autoAvaliacao','Considerando a organização e a participação institucional em eventos, bem como a produção, publicação e/ou veiculação de trabalhos, a divulgação das ações de extensão é:'),
('multiplaEscolha','autoAvaliacao','O processo de ensino-aprendizagem desenvolvido na FABRAS está baseado no diálogo de forma:'),
('multiplaEscolha','autoAvaliacao','Os processos educativos na FAMEV, enquanto trabalho de humanização e de formação de cidadãos capazes de atuar e transformar a sociedade, é:'),
# EIXO 5
('multiplaEscolha','autoAvaliacao','Considerando o tipo de atendimento prestado, específico de cada setor, as instalações dos setores administrativos são:'),
('multiplaEscolha','autoAvaliacao','Considerando a utilização com segurança e autonomia, total ou assistida, dos espaços, mobiliários e equipamentos, a acessibilidade arquitetônica para pessoas com deficiência ou com mobilidade reduzida na biblioteca da FABRAS é:'),
('multiplaEscolha','autoAvaliacao','Considerando a qualidade da iluminação, limpeza, climatização, mobiliário, acesso aos equipamentos de informática ou a rede sem fio, as instalações administrativas são:'),
('multiplaEscolha','autoAvaliacao','Considerando a qualidade da iluminação, climatização, limpeza, organização, mobiliário e espaço disponível para as atividades, as Salas de Aula são:'),
('multiplaEscolha','autoAvaliacao','Considerando a qualidade da iluminação, climatização, limpeza, dos diversos espaços da Instituição são:'),
('multiplaEscolha','autoAvaliacao','Considerando espaço, limpeza, climatização, conservação, equipamentos, quantidade de mesas e cadeiras, os espaços de alimentação (Cantina) da FABRAS são:'),
('multiplaEscolha','autoAvaliacao','Considerando espaço, limpeza, conservação, opções de lazer e distração, os espaços de convivência da FABRAS são:'),
('multiplaEscolha','autoAvaliacao','Considerando quantidade de equipamentos e espaço físico, os laboratórios de ensino são:'),
('multiplaEscolha','autoAvaliacao','Considerando atualização de equipamentos, acessibilidade e disponibilidade de insumos, os laboratórios de ensino são:'),
('multiplaEscolha','autoAvaliacao','Considerando o apoio técnico, manutenção de equipamentos, normas de segurança e atendimento as práticas didáticas, os laboratórios de ensino são:'),
('multiplaEscolha','autoAvaliacao','Considerando atualização e atendimento às necessidades de referências bibliográficas por parte de funcionários e alunos, o acervo da biblioteca é:'),
('multiplaEscolha','autoAvaliacao','Considerando a presença de computadores para pesquisa do acervo, sistema online para reservas, salas de estudo individuais e espaços de estudo coletivo, a estrutura da biblioteca é:'),
('multiplaEscolha','autoAvaliacao','Considerando horas de disponibilidade para atividades extraclasse, quantidade e atualização dos equipamentos, o(s) laboratório(s) de informática são:'),
('multiplaEscolha','autoAvaliacao','Considerando a conservação das instalações e a existência de insumos para a higiene, as instalações sanitárias são:'),



