insert into acadgeral__disciplina (tdisc_id, disc_nome, disc_sigla, disc_ativo, disc_origem)
values 
(1,'','Direito de família','Sim','Universa'),
(1,'','Direito sucessório','Sim','Universa'),
(1,'','Direito Civil','Sim','Universa'),
(1,'','Arbtiragem e mediação de conflitos','Sim','Universa'),
(1,'','Direito Empresarial','Sim','Universa'),
(1,'','Governança Corporativa, Controle Interno e Compliance','Sim','Universa'),
(1,'','Direito Digital','Sim','Universa'),
(1,'','Crimes cibernéticos e técnicas forenses','Sim','Universa'),
(1,'','Direito penal','Sim','Universa'),
(1,'','Direito processual penal ','Sim','Universa'),
(1,'','Direito tributário','Sim','Universa'),
(1,'','Direito processual tributário','Sim','Universa'),
(1,'','Gestão Tributária','Sim','Universa'),
(1,'','Direito do trabalho e da previdência','Sim','Universa'),
(1,'','Gestão do Departamento de Pessoal','Sim','Universa'),
(1,'','Direito Processual do trabalho','Sim','Universa'),
(1,'','Elaboração e Gestão de Contratos ','Sim','Universa'),
(1,'','Negociação Comercial e Negócios Eletrônicos','Sim','Universa'),
(1,'','Direito internacional e comércio exterior','Sim','Universa'),
(1,'','Legislação imobiliária urbana e territorial','Sim','Universa'),
(1,'','Direito Notarial e Registral  ','Sim','Universa'),
(1,'','Licitações públicas','Sim','Universa'),
(1,'','Ciências de Dados e Big data','Sim','Universa'),
(1,'','Redes Sociais Digitais','Sim','Universa'),
(1,'','Lei Geral de Proteção de Dados','Sim','Universa'),
(1,'','Direito da Propriedade Intelectual','Sim','Universa'),
(1,'','Registro de Software, Marcas e Patentes','Sim','Universa'),
(1,'','Análise e Demonstração Financeira e Bancária','Sim','Universa'),
(1,'','Práticas financeiras','Sim','Universa'),
(1,'','Direito Bancário','Sim','Universa'),
(1,'','Gestão do terceiro setor','Sim','Universa'),
(1,'','Oratória','Sim','Universa'),
(1,'','Gestão de Escritórios de Advocacia','Sim','Universa'),
(1,'','Alfabetização e Letramento','Sim','Universa'),
(1,'','Andragogia e educação profissional','Sim','Universa'),
(1,'','Atuação Interdisciplinar e Neuroeducação','Sim','Universa'),
(1,'','Avaliação Teoria e Prática','Sim','Universa'),
(1,'','Currículos, Programas e Projetos Pedagógicos','Sim','Universa'),
(1,'','Desenvolvimento neuropsicomotor e da aprendizagem','Sim','Universa'),
(1,'','Didática do Ensino Superior','Sim','Universa'),
(1,'','Educação das Relações Étnico-Raciais​','Sim','Universa'),
(1,'','Educação de Jovens e Adultos','Sim','Universa'),
(1,'','Educação e Tecnologias','Sim','Universa'),
(1,'','Educação em direitos humanos','Sim','Universa'),
(1,'','Educação Inclusiva','Sim','Universa'),
(1,'','Educação infantil','Sim','Universa'),
(1,'','Educação popular','Sim','Universa'),
(1,'','Gestão educacional','Sim','Universa'),
(1,'','Instrumentos Avaliativos das Linguagens e Processos lógicos-matemáticos','Sim','Universa'),
(1,'','LIBRAS','Sim','Universa'),
(1,'','Linguística Aplicada ao Ensino de Português','Sim','Universa'),
(1,'','Metodologias Ativas','Sim','Universa'),
(1,'','Neurociências e as práticas pedagógicas: jogos, brincadeiras e didática aplicadas a neuroeducação','Sim','Universa'),
(1,'','Neuroeducação e Tecnologias Educacionais​','Sim','Universa'),
(1,'','Português Instrumental','Sim','Universa'),
(1,'','Práticas de secretaria escolar','Sim','Universa'),
(1,'','Processos Cognitivos e Aprendizagem','Sim','Universa'),
(1,'','Processos de aquisição da linguagem e da escrita','Sim','Universa'),
(1,'','Produção de conteúdos para EaD','Sim','Universa'),
(1,'','Psicomotricidade','Sim','Universa'),
(1,'','Transtorno do Espectro Autista','Sim','Universa'),
(1,'','Transtornos e Distúrbios da Aprendizagem','Sim','Universa'),
(1,'','Transtornos psiquiátricos na infância e adolescência','Sim','Universa'),
(1,'','Logística Empresarial','Sim','Universa'),
(1,'','Metrologia e Normatização','Sim','Universa'),
(1,'','Gestão da Produção','Sim','Universa'),
(1,'','Análise de Viabilidade Econômica e Financeira de Projetos','Sim','Universa'),
(1,'','Análise e modelagem de processos','Sim','Universa'),
(1,'','Gestão de Sistema da Informação','Sim','Universa'),
(1,'','Gestão de Custos e Finanças','Sim','Universa'),
(1,'','​Matemática Financeira​','Sim','Universa'),
(1,'','Planejamento e Controladoria Financeira','Sim','Universa'),
(1,'','​Gestão de Estoque​','Sim','Universa'),
(1,'','Gestão de Suprimentos, Logística e Transporte','Sim','Universa'),
(1,'','Gestão de compras e negociação','Sim','Universa'),
(1,'','Logística Reversa','Sim','Universa'),
(1,'','Logística de Armazenagem','Sim','Universa'),
(1,'','Logística de Transportes','Sim','Universa'),
(1,'','​Logística Internacional','Sim','Universa'),
(1,'','Gestão Ambiental','Sim','Universa'),
(1,'','Gerenciamento dos Aspectos e Impactos Ambientais','Sim','Universa'),
(1,'','Meio ambiente, desenvolvimento e sustentabilidade','Sim','Universa'),
(1,'','Energias renováveis','Sim','Universa'),
(1,'','Tratamento da água e efluentes','Sim','Universa'),
(1,'','Gestão de Times - Métodos Ágeis','Sim','Universa'),
(1,'','Análise e Projeto de Software Orientado a Objetos','Sim','Universa'),
(1,'','Cabeamento Estruturado','Sim','Universa'),
(1,'','​Gestão de Materiais','Sim','Universa'),
(1,'','Metodologia da Manutenção','Sim','Universa'),
(1,'','Administração de Materiais','Sim','Universa'),
(1,'','Planejamento Urbano e Cidades Inteligentes','Sim','Universa'),
(1,'','Desenho Técnico Topográfico em CAD','Sim','Universa'),
(1,'','Sustentabilidade na Construção Civil','Sim','Universa'),
(1,'','Modelagem de Projetos de Construção com Tecnologia BIM','Sim','Universa'),
(1,'','Lógica de Programação','Sim','Universa'),
(1,'','Programação em CLP','Sim','Universa'),
(1,'','Macrocontroladores e Microprocessadores','Sim','Universa'),
(1,'','Projetos de Automação Industrial','Sim','Universa'),
(1,'','Citogenética no Diagnóstico Laboratorial','Sim','Universa'),
(1,'','Projeto Geométrico de Estradas','Sim','Universa'),
(1,'','Análise e Projeto de Software orientado à objetos','Sim','Universa'),
(1,'','Ambiente de desenvolvimento para web','Sim','Universa'),
(1,'','Programação - Coding WEB (PHP)','Sim','Universa'),
(1,'','Finanças Corporativas','Sim','Universa'),
(1,'','Estratégia de Gestão e Organização Empresarial','Sim','Universa'),
(1,'','Estratégias de Marketing','Sim','Universa'),
(1,'','Gestão de Tecnologia e Informação em Logística','Sim','Universa'),
(1,'','Logística de Transportes','Sim','Universa'),
(1,'','Logística de Armazenagem','Sim','Universa'),
(1,'','Logística Empresarial','Sim','Universa'),
(1,'','Divisão e modelagem de cargos e salários','Sim','Universa'),
(1,'','​Gestão de Recursos Humanos e Carreiras​','Sim','Universa'),
(1,'','Sistemas de Informações Gerencias de RH​','Sim','Universa'),
(1,'','​Recrutamento, Seleção e Socialização','Sim','Universa'),
(1,'','Gestão de Departamento Pessoal','Sim','Universa'),
(1,'','Análise de Viabilidade Econômica e Financeira de Projetos','Sim','Universa'),
(1,'','Processo Decisório','Sim','Universa'),
(1,'','Jogos Empresariais','Sim','Universa'),
(1,'','Gestão da Inovação e Competitividade','Sim','Universa'),
(1,'','Análise e Demonstração Financeira e Bancária','Sim','Universa'),
(1,'','Meio ambiente, desenvolvimento e sustentabilidade','Sim','Universa'),
(1,'','Gerenciamento dos Aspectos e Impactos Ambientais','Sim','Universa'),
(1,'','Gestão Operacional de Loja','Sim','Universa'),
(1,'','Gestão Hospitalar e Qualidade no Atendimento','Sim','Universa'),
(1,'','Gestão de Serviços de Documentação Hospitalar','Sim','Universa'),
(1,'','Contabilidade de custos','Sim','Universa'),
(1,'','Análise das Demonstrações Contábeis','Sim','Universa'),
(1,'','Contabilidade Intermediária','Sim','Universa'),
(1,'','Controladoria','Sim','Universa'),
(1,'','​Prevenção e Tratamento de Não Conformidades​','Sim','Universa'),
(1,'','Gestão do terceiro setor','Sim','Universa'),
(1,'','Licitações públicas','Sim','Universa'),
(1,'','Estudos avançados de marketing sustentável','Sim','Universa'),
(1,'','Análise e Pesquisa de Mercado','Sim','Universa'),
(1,'','Métricas de marketing','Sim','Universa'),
(1,'','Trade Marketing','Sim','Universa'),
(1,'','Marketing de Eventos​','Sim','Universa'),
(1,'','Marketing Eletrônico e Internacional','Sim','Universa'),
(1,'','Divisão e modelagem de cargos e salários','Sim','Universa'),
(1,'','Gestão Estratégica de Custo','Sim','Universa'),
(1,'','Análise de Crédito e Risco','Sim','Universa'),
(1,'','​Orçamento Empresarial e Fluxo de Caixa​','Sim','Universa'),
(1,'','Planejamento e Controladoria Financeira','Sim','Universa'),
(1,'','Empreendedorismo','Sim','Universa'),
(1,'','Gestão de Startups','Sim','Universa'),
(1,'','Big Data e Ciência dos Dados','Sim','Universa'),
(1,'','Redes Sociais Digitais','Sim','Universa'),
(1,'','Marketing e Propaganda Digital','Sim','Universa'),
(1,'','Marketing de Serviços e do Varejo','Sim','Universa'),
(1,'','Avaliação Nutricional','Sim','Universa'),
(1,'','Gestão de Serviços de Nutrição e Dietética','Sim','Universa'),
(1,'','​Nutrição e Dietética​','Sim','Universa'),
(1,'','Técnica dietética básica','Sim','Universa'),
(1,'','Suplementação Nutricional, Recursos Ergogênicos e Fitoterápicos no Esporte','Sim','Universa'),
(1,'','Suplementação Nutricional e Fitoterapia nas Doenças','Sim','Universa'),
(1,'','Regulação, controle, avaliação e auditoria em saúde','Sim','Universa'),
(1,'','Segurança, Meio Ambiente, Saúde e Responsabilidade Social','Sim','Universa'),
(1,'','Suplementação Nutricional e Fitoterapia na Saúde','Sim','Universa'),
(1,'','Exercício físico e o idoso','Sim','Universa'),
(1,'','Fisioterapia nas doenças osteoarticulares','Sim','Universa'),
(1,'','Exercício e Treinamento Desportivo','Sim','Universa'),
(1,'','Fisioterapia nas Doenças Cardiorespiratórias','Sim','Universa'),
(1,'','Geriatria e Gerontologia','Sim','Universa'),
(1,'','Adaptações Funcionais no Idoso','Sim','Universa'),
(1,'','Neurologia e Genética do Envelhecimento','Sim','Universa'),
(1,'','Nutrição e o Idoso','Sim','Universa'),
(1,'','Assistência de Enfermagem em Oncologia Cirúrgica','Sim','Universa'),
(1,'','Assistência de Enfermagem em Oncologia Clínica','Sim','Universa'),
(1,'','Assistência de Enfermagem em Fim de Vida','Sim','Universa'),
(1,'','​Bases Farmacológicas, Terapia Antineoplásica e Hemoterapia','Sim','Universa'),
(1,'','Bioética e Assistência Oncológica','Sim','Universa'),
(1,'','Comunicação em Situações Difíceis no Tratamento Oncológico','Sim','Universa'),
(1,'','Quimioterapia: conceito, modalidades e aspectos de biossegurança','Sim','Universa'),
(1,'','Controle e prevenção de infecção hospitalar','Sim','Universa'),
(1,'','Gerenciamento em unidades oncológicas','Sim','Universa'),
(1,'','Bioética e Biossegurança','Sim','Universa'),
(1,'','Vigilância Sanitária, Epidemiológica e Ambiental','Sim','Universa'),
(1,'','Higiene e Vigilância Sanitária','Sim','Universa'),
(1,'','Arquitetura Hospitalar','Sim','Universa'),
(1,'','Auditoria Hospitalar','Sim','Universa'),
(1,'','Comissões Hospitalares','Sim','Universa'),
(1,'','Gestão de Serviços de Documentação Hospitalar','Sim','Universa'),
(1,'','Gestão Hospitalar e Qualidade no Atendimento','Sim','Universa'),
(1,'','Ouvidoria Hospitalar','Sim','Universa'),
(1,'','Gerenciamento de Perigos e Riscos à Saúde','Sim','Universa'),
(1,'','Gestão de Planos de Saúde','Sim','Universa'),
(1,'','Gestão do Financiamento na Saúde','Sim','Universa'),
(1,'','Gestão do Processo e da Força de Trabalho em Saúde','Sim','Universa'),
(1,'','Modelos e Gestão de Serviços em Saúde','Sim','Universa'),
(1,'','Regulação, controle, avaliação e auditoria em saúde','Sim','Universa'),
(1,'','Sistema de Informação para à Saúde','Sim','Universa'),
(1,'','​Gestão de Tecnologia Hospitalar​','Sim','Universa'),
(1,'','​Gestão de serviços laboratoriais e setores especializados','Sim','Universa'),
(1,'','Gestão da Qualidade','Sim','Universa'),
(1,'','Gestão de Custos, Riscos e Perdas - GCRP','Sim','Universa'),
(1,'','​Gestão de Estoque​','Sim','Universa'),
(1,'','Gestão de Serviços de Farmácia','Sim','Universa'),
(1,'','Gestão de Suprimentos, Logística e Transporte','Sim','Universa'),
(1,'','Saúde Mental e Assistência Farmacêutica','Sim','Universa'),
(1,'','Psicofarmacologia Clínica','Sim','Universa'),
(1,'','Toxicologia analítica: clínica e forense','Sim','Universa'),
(1,'','Hematologia Clínica','Sim','Universa'),
(1,'','Farmácia Clínica e Atenção Farmacêutica','Sim','Universa'),
(1,'','Patologia Geral','Sim','Universa'),
(1,'','Covid-19, Impactos e Prevenção','Sim','Universa'),
(1,'','Desenvolvimento Neuropsicomotor e da Aprendizagem','Sim','Universa'),
(1,'','Psicologia do Desenvolvimento','Sim','Universa'),
(1,'','Neurociências e as Práticas Pedagógicas: Jogos, Brincadeiras e Didática Aplicadas à neuroeducação.','Sim','Universa'),
(1,'','Psicomotricidade','Sim','Universa'),
(1,'','Psicologia da Aprendizagem','Sim','Universa'),
(1,'','Atuação Interdisciplinar e Neuroeducação','Sim','Universa'),
(1,'','Segurança do Trabalho e Saúde Ocupacional','Sim','Universa'),
(1,'','Suporte Emergencial à Vida e Atendimento Pré-Hospitalar','Sim','Universa'),
(1,'','Meio Ambiente e Qualidade de Vida','Sim','Universa'),
(1,'','Ergonomia e Medicina do Trabalho','Sim','Universa'),
(1,'','Psicologia do Trabalho','Sim','Universa'),
(1,'','Higiene Ocupacional e Prenvenção de Riscos Ambientais','Sim','Universa'),
(1,'','Lógica de Programação','Sim','Universa'),
(1,'','Introdução a Banco de Dados','Sim','Universa'),
(1,'','Ambiente de desenvolvimento para web','Sim','Universa'),
(1,'','Tecnologias e Linguagens de Banco de Dados','Sim','Universa'),
(1,'','Introdução ao Coding Web','Sim','Universa'),
(1,'','Introdução ao Coding Mobile','Sim','Universa'),
(1,'','Análise e Projeto de Software Orientado a Objetos','Sim','Universa'),
(1,'','Human centred design','Sim','Universa'),
(1,'','Gestão de Times - Métodos Ágeis','Sim','Universa'),
(1,'','Ilustração e tratamento de imagens 2D - Adobe Photoshop','Sim','Universa'),
(1,'','Web design em WordPress','Sim','Universa'),
(1,'','Introdução a redes de computadores e protocolos de comunicação','Sim','Universa'),
(1,'','Introdução à segurança da informação','Sim','Universa'),
(1,'','Administração de Sistema Operacional Livre – Linux','Sim','Universa'),
(1,'','Administração de Sistema Operacional Proprietário – Windows Server','Sim','Universa'),
(1,'','Cabeamento Estruturado','Sim','Universa'),
(1,'','Tecnologias e Linguagens de Banco de Dados','Sim','Universa'),
(1,'','Administração do SGBD PostgreSQL','Sim','Universa'),
(1,'','Introdução à segurança da informação','Sim','Universa'),
(1,'','Administração de Sistema Operacional Livre – Linux','Sim','Universa'),
(1,'','Análise de Mercado: Tendência, Comportamento e Movimento','Sim','Universa'),
(1,'','Crimes cibernéticos e técnicas forenses','Sim','Universa'),
(1,'','Ciências de Dados e Big Data','Sim','Universa'),
(1,'','Internet das coisas IoT','Sim','Universa'),
(1,'','Inteligência Artificial','Sim','Universa'),
(1,'','Gestão de Riscos','Sim','Universa'),
(1,'','Linguagem de Programação WEB (PHP)','Sim','Universa'),
(1,'','Qualidade em Software','Sim','Universa'),
(1,'','Teste em Software','Sim','Universa'),
(1,'','Gestão de Recursos Humanos e Carreiras','Sim','Universa'),
(1,'','Gestão da Inovação e Competitividade','Sim','Universa'),
(1,'','Gestão de Sistema de Informação','Sim','Universa'),
(1,'','Liderança e Gestão de Equipes','Sim','Universa'),
(1,'','Sistemas de Informação para a Saúde','Sim','Universa'),
(1,'','Sistemas de Informação Gerenciais','Sim','Universa'),
(1,'','Gestão de Serviços de Tecnologia Hospitalar','Sim','Universa'),
(1,'','Programação - Coding Mobile (JAVA)','Sim','Universa'),
(1,'','Roteirização de Jogos Digitais','Sim','Universa'),
(1,'','Fundamentos Contábeis','Sim','Universa'),
(1,'','Finanças Corporativas','Sim','Universa'),
(1,'','Sistemas de Informação Gerenciais em RH','Sim','Universa'),
(1,'','Sistemas e Multimídia','Sim','Universa'),
(1,'','Ilustração e Criação de Imagens Vetorias - Adobe Illustrator','Sim','Universa'),
(1,'','Web design em WordPress','Sim','Universa')